### ISSUE TITLE
Transfer repo to org

### ISSUE THREAD

**Issue by Conni2461** [noahares/telescope-bibtex#1]
Hey,

i am a core member of telescope and i really like your extension. I have some thoughts and improvements for the code but we can talk about that later.

My question right now do you wanna transfer that repo to the https://github.com/nvim-telescope org? You will obviously have admin permissions :)

Best regards

**Comment by noahares** [comment]
Hi,
I am glad you like it. This is only my second lua project (and also second neovim plugin), so I would appreciate any suggestions to my code. 
I would love to contribute by tranfering it to the org. Hopefully more people can find and use it this way :)
Let me know when I can transfer the repo.

**Comment by Conni2461** [comment]
Okay i currently try to figure out how to progress. 
- I could create a repo: `nvim-telescope/telescope-bibtex.nvim`
- give you rights
- you create do a new `git remote` and push your current tree to that `remote`

**Comment by noahares** [comment]
That should work.

**Comment by Conni2461** [comment]
Okay i try to give some hints :) Hope i give not away too much

1. Reading dir

https://github.com/noahares/telescope-bibtex/blob/431554e2ef63d0f9aee8d6d0e96ad6c1650624ea/lua/telescope-bibtex.lua#L26

You no longer have to call a process to do that. You can call plenary.scan like that (all in lua):
```lua
  local scan = require('plenary.scandir')

  local results = {}
  scan.scan_dir('.', { depth = 1, search_pattern = '.*%.bib', on_insert = function(file)
    file = file:sub(3)

    local result = read_file(file)
    for _, entry in pairs(result) do
      table.insert(results, entry)
    end
  end})
```
2. Reading files

https://github.com/noahares/telescope-bibtex/blob/431554e2ef63d0f9aee8d6d0e96ad6c1650624ea/lua/telescope-bibtex.lua#L12-L23

I don't really like io.lines. Its not really the fastest way of reading a file. neovim has libuv and lua bindings that give us super fast `fs_` operations. That also powers scan_dir. My alt would be use plenary.path which has a iter function.
```lua
local Path = require('plenary.path')

local read_file = function(file)
  local p = Path:new(file)
  if not p:exists() then return {} end
  for line in p:iter() do
    print(line)
  end
end
```

3. Previewer

https://github.com/noahares/telescope-bibtex/blob/431554e2ef63d0f9aee8d6d0e96ad6c1650624ea/lua/telescope-bibtex.lua#L52
That is the same as not passing in anything. We are just constructing a table here and if a key is not present its nil anyway.

But i would love to support previewer. I could imagine having the previewer show the contents of that bibtex entry. I can help you display it. We have a super easy way to do that. You just need to store it in a string after that part is done, i will help you with displaying.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-bibtex.nvim

I will invite you in a sec

Edit: done

**Comment by noahares** [comment]
Thank you for the hints. Plenary sounds really cool. Will check it out on the weekend. 
Regarding the previewer: I wanted to do this as well, but did not yet have the time to dig into it. Storing it in a string and then displaying it makes sense. 

I will have some free time this weekend and see what I can get done.

**Comment by Conni2461** [comment]
Sounds good to me :)

Just open a PR and we can continue the discussion :)

I am closing this issue for now
